DROP DATABASE IF EXISTS BOT_MANAGER;

CREATE DATABASE BOT_MANAGER;

USE BOT_MANAGER;

CREATE TABLE UTENTI(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(200) UNIQUE NOT NULL, 
    PASSWORD VARCHAR(200) NOT NULL,
    EMAIL VARCHAR(256) NOT NULL UNIQUE
);

CREATE TABLE BOT(
	ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    TOKEN VARCHAR(47) UNIQUE NOT NULL,
    ID_UTENTE INT,
    ISALIVE TINYINT,
    FOREIGN KEY (ID_UTENTE) REFERENCES UTENTI(ID)
);

CREATE TABLE TIPICOMANDO(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM('TEXT','API','KEYBOARD') UNIQUE
);

CREATE TABLE COMANDI(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(300) NOT NULL,
	ID_TIPO INTEGER,
    ID_BOT INTEGER,
    FOREIGN KEY (ID_BOT) REFERENCES BOT(ID),
	FOREIGN KEY (ID_TIPO) REFERENCES TIPICOMANDO(ID)
);

CREATE TABLE TESTO(
	ID INT PRIMARY KEY,
	RISPOSTA VARCHAR(500) NOT NULL,
	FOREIGN KEY(ID) REFERENCES COMANDI(ID)
);

INSERT INTO UTENTI VALUES(NULL,'PEDRO','3742674324732','PEDR@GMAIL.COM');
INSERT INTO BOT VALUES('1726299570:AAFc_QNlpTcX4WtQjxjx81KdTiVZQDADOEg',1,1);
INSERT INTO TIPICOMANDO VALUES(NULL,'TEXT'),(NULL,'API'),(NULL,'KEYBOARD');
INSERT INTO COMANDI VALUES(NULL, 'SALUTA', 1);
INSERT INTO TESTO VALUES(1,'CIAO AMICO');

SELECT * FROM UTENTI;
