CREATE DATABASE BOT;

USE BOT;

CREATE TABLE UTENTI(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(200) UNIQUE NOT NULL, 
    PASSWORD VARCHAR(200) NOT NULL,
    EMAIL VARCHAR(256) NOT NULL UNIQUE
);

CREATE TABLE MANAGER(
    TOKEN VARCHAR(47) PRIMARY KEY,
    ID_UTENTE INT,
    ISALIVE TINYINT,
	FOREIGN KEY (ID_UTENTE) REFERENCES UTENTI(ID)
);

-- CREATE TABLE COMANDI(

-- );