DROP DATABASE IF EXISTS BOT_APPLICATION;

CREATE DATABASE BOT_APPLICATION;

USE BOT_APPLICATION;

CREATE TABLE UTENTI(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(200) UNIQUE NOT NULL, 
    PASSWORD VARCHAR(200) NOT NULL,
    EMAIL VARCHAR(256) NOT NULL UNIQUE
);

CREATE TABLE BOT(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    TOKEN VARCHAR(47) UNIQUE NOT NULL,
    ID_UTENTE INT,
    ISALIVE TINYINT,
    FOREIGN KEY (ID_UTENTE) REFERENCES UTENTI(ID)
);

CREATE TABLE TIPICOMANDO(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	TIPO VARCHAR(20) UNIQUE
);

CREATE TABLE COMANDI(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(300) NOT NULL,
	ID_TIPO INTEGER,
	ID_BOT INTEGER,
    HELP_MSG VARCHAR(500) NOT NULL,
	FOREIGN KEY (ID_BOT) REFERENCES BOT(ID),
	FOREIGN KEY (ID_TIPO) REFERENCES TIPICOMANDO(ID)
);

CREATE TABLE TESTUALI(
	ID INT PRIMARY KEY,
	NUM_ARGOMENTI INTEGER,
	RISPOSTA VARCHAR(500) NOT NULL,
	FOREIGN KEY(ID) REFERENCES COMANDI(ID)
);

CREATE TABLE API(
	ID INT PRIMARY KEY,
	FUNZIONE VARCHAR(40) UNIQUE NOT NULL,
	FOREIGN KEY(ID) REFERENCES COMANDI(ID)
);

INSERT INTO UTENTI VALUES(NULL,'PEDRO','3742674324732','PEDR@GMAIL.COM');
INSERT INTO BOT VALUES(NULL, '1726299570:AAFc_QNlpTcX4WtQjxjx81KdTiVZQDADOEg',1,1);
INSERT INTO TIPICOMANDO VALUES(NULL,'TEXT'),(NULL,'API'),(NULL,'KEYBOARD');
INSERT INTO COMANDI VALUES(NULL, '/SALUTA', 1, 1,'COMANDO UTILE PER SALUTARE UNA PERSONA SPECIFICA'),(NULL, '/SALUTA1', 1, 1, "COMANDO UTILE PER SALUTARE UNA PERSONA NON SPECIFICA");
INSERT INTO TESTUALI VALUES(1, 1, 'CIAO AMICO {} CARISSIMO'),(2, 0,'CIAO AMICO CARISSIMO');
INSERT INTO COMANDI VALUES(NULL, '/SALUTA3', 1, 1, "COMANDO UTILE PER SALUTARE DUE PERSONE SPECIFICHE");
INSERT INTO TESTUALI VALUES(3, 2, 'CIAO AMICO {} CARISSIMO E ANCHE {}');
INSERT INTO COMANDI VALUES(NULL, '/IMAGE', 2, 1, "COMANDO UTILE PER OTTENERE DELLE IMMAGINI");
INSERT INTO API VALUES(4,'get_image');



SELECT * FROM BOT;
